version: '3'

services:
  database:
    image: mariadb:10
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
      MARIADB_USER: ${MARIADB_USER:-cotton}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
  php:
    build:
      context: docker/php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www
    depends_on:
      - database
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - php
